import{a as f,i as l,S as p}from"./assets/vendor-9a8cfc74.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const m="43943872-0cd26c97fed3a84845e31fcef";function h(s){return f.get(`https://pixabay.com/api/?key=${m}&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>r.data.hits).catch(r=>console.error(r))}function g(s,r){if(s.length===0){l.error({title:"Error",message:"Изображения, соответствующие вашему запросу, не найдены. Пожалуйста, попробуйте еще раз."});return}const n=s.map(o=>`
    <div class="image-card">
      <a href="${o.largeImageURL}"><img src="${o.webformatURL}" alt="${o.tags}" title=""/></a>
      <div class="image-info">
        <p><span>Просмотры: </span>${o.views}</p>
        <p><span>Загрузки: </span>${o.downloads}</p>
        <p><span>Лайки: </span>${o.likes}</p>
        <p><span>Комментарии: </span>${o.comments}</p>
      </div>
    </div>
  `).join("");r.innerHTML=n}const y=document.querySelector("#search-form"),d=document.querySelector("#search-input"),a=document.querySelector("#gallery"),u=document.querySelector("#loader");let c;y.addEventListener("submit",s=>{s.preventDefault();const r=d.value.trim();if(!r){l.warning({title:"Warning",message:"Пожалуйста, введите ключевое слово для поиска"});return}u.classList.remove("hidden"),h(r).then(n=>{if(u.classList.add("hidden"),a.innerHTML="",g(n,a),a.querySelectorAll(".image-card a").length>0){if(c=new p(".image-card a",{}),s.target.nodeName!=="IMG")return;c?c.refresh():console.error("Lightbox is not initialized.")}else console.error("No images found for lightbox to handle.");d.value=""}).catch(n=>{console.error(n),l.error({title:"Error",message:"Произошла ошибка при загрузке изображений. Пожалуйста, попробуйте еще раз."})})});
//# sourceMappingURL=commonHelpers.js.map
